Add master_return_strategy feature
bloomberg/salt pull request #4
Opened 2019-02-08 17:52 UTC by sbrennan4

### What does this PR do?

If the `master_type` is set to `str`, then this option controls the master return strategy. Can be `source` or `any`. If set to `source`, then the minion will only attempt to return the job results to the master that sent the job. If set to `any`, then the minion will attempt to return the job results to the master that sent the job but if that fails, then the minion will attempt to return the job results to the other masters until successful or the master list has been exhausted. `master_alive_interval` must also be set. This is used to keep track of which masters are currently connected.

### What issues does this PR fix or reference?

https://jira5.prod.bloomberg.com/browse/RDTISALT-2569

### Previous Behavior

If a master sends a job to a minion and then goes down before receiving the job return, then that data is lost to the master(s) forever.

### New Behavior

If the source master goes down before receiving the job return then try to send the return to the other connected masters.

### Tests written?

No

### Commits signed with GPG?

No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

2019-02-08 17:53 UTC, sbrennan4 commented
Please note, I've left a lot of `log.error` statements in here for the demo.

2019-02-11 18:08 UTC, mattp- requested changes

2019-02-11 18:08 UTC, mattp- commented on salt/minion.py
> +    @tornado.gen.coroutine
why did you add this? doesn't like its being used as a coro

2019-02-11 18:08 UTC, mattp- commented on salt/minion.py
> +    def _handle_tag_master_return(self, tag, data):
your general approach makes sense, but I think what would be cleaner is if instead of adding this _handle_tag_master_return so each minion acts on the return conditionally, you instead put this logic in MinionManager.handle_event, which has knowledge of which minions are connected (and based on the master_return_strategy can do the right thing). It might also make sense to have an 'all' strategy that sends the result everywhere?
I'd also rename +_handle_tag_schedule_return to _handle_tag_master_return and let that unconditionally return to its master.

2019-02-11 18:08 UTC, mattp- commented on salt/minion.py
> +    @tornado.gen.coroutine
ditto below, its not clear why you added this

2019-02-11 18:08 UTC, mattp- commented on salt/minion.py
> +            log.error('connected_masters1 = %s', self.opts['connected_masters'])
we should clean this logging up. but also wrt the other comment, we shouldn't need to keep track of connected masters if we move the logic to minionmanager.handle_event

2019-02-12 15:20 UTC, sbrennan4 commented on salt/minion.py
> +    @tornado.gen.coroutine
When not a coro, I think it's taking too long for all the minions to run this routine and update their connection status. For example, if I have 3 masters and I initiate a command on master1 then stop master1 and master2, then master1 will timeout and forward the command to masters 2 and 3. At this point, the minion for master2 does not realize it's disconnected and attempts to handle the return which, in turn, times out and forwards the event to the minion for master3. It works, but takes longer. 

Additionally, when not a coro, the log messages don't show up.

2019-02-12 15:39 UTC, sbrennan4 commented on salt/minion.py
> +    def _handle_tag_master_return(self, tag, data):
I don't think MinionManager _does_ keep track of which minions are connected after the initial tune_in. I also don't think MinionManager is aware when a job return fails so how would it send it to another minion? Using the minion event bus seems to be the way to communicate between minion instances. Please correct me if I'm wrong and provide more detail if you have further insight around this approach. 

I agree that `all` would make this feature complete but I've been forcing myself to _not_ implement it at this time in the name not wasting time on a feature we may never use.

`_handle_tag_schedule_return` is literally for handling schedule return events (i.e. tag = __schedule_return). Are you suggesting we fire `__schedule_return` on timeout instead of `master_return` and combine the `_handle_tag_master_return` and `_handle_tag_schedule_return` functions?

2019-02-12 15:45 UTC, sbrennan4 commented on salt/minion.py
> +            log.error('connected_masters1 = %s', self.opts['connected_masters'])
I'll clean up the logging after the demo.

2019-02-12 16:51 UTC, sbrennan4 commented on salt/minion.py
> +    def _handle_tag_master_return(self, tag, data):
I'm looking at this again and I think I'm starting to pick up what you're putting down. Let me run with this for a bit.

2019-02-12 18:31 UTC, sbrennan4 commented on salt/minion.py
> +            log.error('connected_masters1 = %s', self.opts['connected_masters'])
I've removed all the logic used to keep track of connected masters and moved everything to MinionManager.

2019-02-12 19:52 UTC, mattp- commented on salt/minion.py
> +    @tornado.gen.coroutine
since MinionManager.handle_event yields each return here turning this into a coro should be ok. its not that the log messages didn't show up, they were just being handled in serial.

2019-02-12 19:57 UTC, sbrennan4 commented on salt/minion.py
> +    def _handle_tag_master_return(self, tag, data):
I've moved all the logic to the MinionManager class and I agree this is much cleaner. I think it's fine to keep the handling of `master_return` and `__schedule_return` events explicit and separate.

2019-02-15 19:20 UTC, sbrennan4 commented
Will close this PR and submit upstream.

2019-02-15 19:20 UTC, closed without merging